 try{
	 thisDoesnotExhist(5,5);
 }
 catch(err){
	 alert(err);
 }